/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDI.Digital.Telas;

import BDI.Digital.DAL.ModuloConexao;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silvio
 */
public class TelaDeletarHorarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaDeletarHorarios
     */
    DefaultTableModel dtmHorarios;
    Connection conexao = null;
    
    public TelaDeletarHorarios() {
        initComponents();
        conexao = ModuloConexao.conector();
        createTable();
    }
    
    public void createTable(){
        dtmHorarios = (DefaultTableModel)tabelaHorarios.getModel();
        dtmHorarios.setNumRows(0);
        tabelaHorarios.getColumnModel().getColumn(0).setMaxWidth(100);
        tabelaHorarios.getColumnModel().getColumn(0).setPreferredWidth(90);
        tabelaHorarios.getColumnModel().getColumn(1).setMaxWidth(50);
        tabelaHorarios.getColumnModel().getColumn(2).setMaxWidth(100);
        tabelaHorarios.getColumnModel().getColumn(2).setPreferredWidth(90);
        consultaHorarios();
    }
    
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    public void consultaHorarios(){
        String sql =    "SELECT HORARIOS.cod_horario, HORARIOS.horario, LINHAS.cod_linha, LINHAS.prefixoLinha, LINHAS.itinerarioLinha\n" +
                        "FROM HORARIOS_POR_LINHA \n" +
                        "INNER JOIN HORARIOS ON HORARIOS.cod_horario = HORARIOS_POR_LINHA.cod_horario\n" +
                        "INNER JOIN LINHAS ON LINHAS.cod_linha = HORARIOS_POR_LINHA.cod_linha order by HORARIOS.horario;";
        ResultSet rs = null;
        PreparedStatement pst = null;
        
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                Object[] dados = {rs.getString(1), rs.getString(2), rs.getString(3),
                rs.getString(4), rs.getString(5)};
                dtmHorarios.addRow(dados);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHorarios = new javax.swing.JTable();
        btnDeletarHorario = new javax.swing.JButton();

        setClosable(true);
        setTitle("Deletar Horários");

        tabelaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Horario", "Horário", "Codigo Linha", "Prefixo", "Itinerário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaHorarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaHorarios);

        btnDeletarHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BDI/Digital/Icones/if_file_delete_48762.png"))); // NOI18N
        btnDeletarHorario.setToolTipText("Deletar Horário");
        btnDeletarHorario.setBorderPainted(false);
        btnDeletarHorario.setContentAreaFilled(false);
        btnDeletarHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeletarHorario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletarHorario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarHorarioActionPerformed
        // TODO add your handling code here:
        if(tabelaHorarios.getSelectedRow() != -1){
            int k = tabelaHorarios.getSelectedRow();
            String idHorario = (String) tabelaHorarios.getValueAt(k, 0);
            String idLinha = (String) tabelaHorarios.getValueAt(k, 2);
            String sqlDeletarHorario = "DELETE FROM HORARIOS_POR_LINHA WHERE cod_horario = ? AND cod_linha = ?";
            PreparedStatement pst = null;
            
            try {
                pst = conexao.prepareStatement(sqlDeletarHorario);
                pst.setString(1, idHorario);
                pst.setString(2, idLinha);
                pst.executeUpdate();
                createTable();
                JOptionPane.showMessageDialog(null, "Registro deletado com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_btnDeletarHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarHorario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHorarios;
    // End of variables declaration//GEN-END:variables
}
