/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDI.Digital.Telas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import BDI.Digital.DAL.ModuloConexao;
import java.awt.Dimension;
import java.sql.Connection;

/**
 *
 * @author Silvio
 */
public class TelaCadastraLinha extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastraLinha
     */
    
    Connection conexao = null;
    
    public TelaCadastraLinha() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    public void cadastraLinha(){
        String sqlCadastraLinha = "INSERT INTO LINHAS (prefixoLinha, itinerarioLinha) VALUES(?,?)";
        PreparedStatement pstCadastraLinha = null;
        
        try {
            pstCadastraLinha = conexao.prepareStatement(sqlCadastraLinha);
            pstCadastraLinha.setString(1, txtPrefixo.getText().toUpperCase());
            pstCadastraLinha.setString(2, txtItinerario.getText().toUpperCase());
            pstCadastraLinha.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrefixo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtItinerario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLimparForm = new javax.swing.JButton();
        btnSalvarLinha = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Linhas");

        jLabel1.setText("Prefixo:");

        jLabel2.setText("Itinerário:");

        btnLimparForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BDI/Digital/Icones/if_CCleaner_33788.png"))); // NOI18N
        btnLimparForm.setBorderPainted(false);
        btnLimparForm.setContentAreaFilled(false);
        btnLimparForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormActionPerformed(evt);
            }
        });

        btnSalvarLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BDI/Digital/Icones/if_file_add_48761.png"))); // NOI18N
        btnSalvarLinha.setBorderPainted(false);
        btnSalvarLinha.setContentAreaFilled(false);
        btnSalvarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparForm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarLinha)
                    .addComponent(btnLimparForm))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormActionPerformed

    private void btnSalvarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLinhaActionPerformed
        // TODO add your handling code here:
        if(!txtItinerario.getText().isEmpty() && !txtPrefixo.getText().isEmpty()){
            cadastraLinha();
        }
        else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!");
        }
    }//GEN-LAST:event_btnSalvarLinhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparForm;
    private javax.swing.JButton btnSalvarLinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtItinerario;
    private javax.swing.JTextField txtPrefixo;
    // End of variables declaration//GEN-END:variables
}
